Added a point to the troubleshooting of docker node
Concordium/concordium.github.io pull request #564
Opened 2022-08-04 12:18 UTC by shjortConcordium

## Purpose

Add what I did to make the docker setup work, on my setup.

## Checklist

- [x] My code follows the style of this project.
- [x] The code compiles without warnings.
- [x] I have performed a self-review of the changes.
- [x] I have documented my code, in particular the intent of the
      hard-to-understand areas.

2022-08-04 12:50 UTC, dg-concordium requested changes

2022-08-04 12:50 UTC, dg-concordium commented on source/mainnet/net/guides/run-node.rst
> +Some users on Ubuntu have reported the node does not have internet access. In this case, adding `network_mode: bridge` to each service, might solve this problem:
```suggestion
Some users on Ubuntu have reported the node does not have internet access. In this case, adding `network_mode: bridge` to each service might solve this problem:
```

2022-08-04 16:11 UTC, abizjak approved these changes

2022-08-05 10:46 UTC, dg-concordium approved these changes

2022-08-05 10:46 UTC, merged