Out-of-band catchup with the new `--download-blocks-from` parameter
Concordium/concordium.github.io pull request #580
Opened 2022-08-19 11:35 UTC by mkmks

## Purpose

The node is getting a new, faster incremental out-of-band catchup mechanism (https://github.com/Concordium/concordium-node/issues/371). It's triggered by the use of the `--download-blocks-from` parameter. First-time node operators should know about it.

## Changes

Getting started guides for Ubuntu, MacOS and Windows now mention `--download-blocks-from` as the preferred way to catch up out-of-band.

## Checklist

- [x] My code follows the style of this project.
- [x] The code compiles without warnings.
- [x] I have performed a self-review of the changes.
- [x] I have documented my code, in particular the intent of the
      hard-to-understand areas.
- [x] (If necessary) I have updated the CHANGELOG.

## CLA acceptance

By submitting the contribution I accept the terms and conditions of the
Contributor License Agreement v1.0
- link: https://developers.concordium.com/CLAs/Contributor-License-Agreement-v1.0.pdf

- [x] I accept the above linked CLA.

2022-09-24 08:54 UTC, abizjak requested changes

2022-09-24 08:54 UTC, abizjak commented on source/mainnet/net/guides/run-node-macos.rst
> +   The latter does not and slows down the node startup significantly.
This is not a recommendation we have agreed on and it should not be stated as such. Once the node is caught up they should remove this from the configuration file. For normal operation this is useless (e.g., if they did a node upgrade or maintenance), will slow down node startup a bit, and will put a load on our servers.

2022-09-24 08:54 UTC, abizjak commented on source/mainnet/net/guides/run-node-ubuntu.rst
> +   The latter does not and slows down the node startup significantly.
Same here.

2022-09-24 08:54 UTC, abizjak commented on source/mainnet/net/nodes/run-node-ubuntu.rst
> +   database. The latter does not and slows down the node startup significantly.
And here.

2022-09-26 17:23 UTC, abizjak approved these changes

2022-09-27 06:50 UTC, dg-concordium approved these changes

2022-09-27 11:34 UTC, merged