Tools release December 2022
Concordium/concordium.github.io pull request #684
Opened 2022-12-06 12:00 UTC by dg-concordium

## Purpose

Inform users about updates to Concordium tools in December.

## Changes

Release notes, downloads links.

## Checklist

- [X] My code follows the style of this project.
- [ ] The code compiles without warnings.
- [ ] I have performed a self-review of the changes.
- [ ] I have documented my code, in particular the intent of the
      hard-to-understand areas.
- [ ] (If necessary) I have updated the CHANGELOG.

## CLA acceptance

_Remove if not applicable.

By submitting the contribution I accept the terms and conditions of the
Contributor License Agreement v1.0
- link: https://developers.concordium.com/CLAs/Contributor-License-Agreement-v1.0.pdf

- [ ] I accept the above linked CLA.

2022-12-06 12:01 UTC, dg-concordium commented
The update to cargo should be reflected in the SC documentation. @abizjak

2022-12-13 12:20 UTC, mh-concordium requested changes

2022-12-13 12:20 UTC, mh-concordium commented on source/mainnet/net/installation/downloads-testnet.rst
>     - SHA256 checksum of the download: 3ed9f3878d07c53d6f2233d4832fed45eea74363e1f8671d42be45043dd3937b
```suggestion
   - SHA256 checksum of the download: bd39487463b45c7bbbbcdeeb1cbbd0f4fe8e62041869aa3db9cdcf331ed8a049
```

2022-12-13 12:20 UTC, mh-concordium commented on source/mainnet/variables.rst
> +.. |cargo-linux-checksum| replace:: xxxxxxxx
```suggestion
.. |cargo-linux-checksum| replace:: 96e7d4de085147d57aeff17f92c0cad16fd4039434eea7eb67dfdad28b898434
```

2022-12-14 07:24 UTC, abizjak approved these changes

2022-12-14 07:25 UTC, merged