Added documentation for base64 commands in cargo concordium
Concordium/concordium.github.io pull request #739
Opened 2023-01-24 13:28 UTC by DOBEN

## Purpose

closes #736

2023-01-24 17:29 UTC, abizjak approved these changes
Looks good. We should combine this PR with a release of the new tool version.

2023-01-24 17:29 UTC, abizjak commented on source/mainnet/smart-contracts/guides/build-schema.rst
> +   $cargo concordium schema-base64 --schema "schema/schema.bin" --out "-"
Are the quotes around `-` needed?

2023-01-25 07:23 UTC, dg-concordium requested changes

2023-01-25 07:23 UTC, dg-concordium commented on source/mainnet/smart-contracts/guides/build-schema.rst
> +output in base64 format that is currently supported in the browser wallet. When building
Can you include the variables.rst at the top of the file and then replace browser wallet with |bw| so that it gets the correct product name?

2023-01-25 07:23 UTC, dg-concordium commented on source/mainnet/smart-contracts/guides/build-schema.rst
> +   - The command ``schema-base64`` and the flag ``--schema-base64-out`` convert the schema into base64 format. This is the format that is currently used by the browser wallet and most of our front-en
Same as for other instance of browser wallet.

2023-01-25 09:10 UTC, DOBEN commented on source/mainnet/smart-contracts/guides/build-schema.rst
> +   $cargo concordium schema-base64 --schema "schema/schema.bin" --out "-"
Quotes are not needed. I removed them.

2023-01-25 10:17 UTC, dg-concordium approved these changes

2023-01-30 09:16 UTC, merged