Mainnet node release April 2023
Concordium/concordium.github.io pull request #787
Opened 2023-03-30 07:56 UTC by dg-concordium

## Purpose

Inform users about changes in Mainnet node release.

## Changes

Release notes, downloads, update to Ubuntu node file, previous downloads

## Checklist

- [ ] My code follows the style of this project.
- [ ] The code compiles without warnings.
- [ ] I have performed a self-review of the changes.
- [ ] I have documented my code, in particular the intent of the
      hard-to-understand areas.
- [ ] (If necessary) I have updated the CHANGELOG.

## CLA acceptance

_Remove if not applicable.

By submitting the contribution I accept the terms and conditions of the
Contributor License Agreement v1.0
- link: https://developers.concordium.com/CLAs/Contributor-License-Agreement-v1.0.pdf

- [ ] I accept the above linked CLA.

2023-04-21 07:15 UTC, abizjak approved these changes
Looks good.

2023-04-21 09:35 UTC, dg-concordium commented on source/mainnet/net/guides/run-node-ubuntu.rst
> +Since version 5.3.0 of the node the collector uses the GRPC V2 interface. Therefore, in order to run the collector, it is required that the node which the collector connects to has the GRPC V2 interf
Yes, just forgot to update it from the original.

2023-04-25 05:54 UTC, mh-concordium requested changes
Looks good, I only noticed a minor thing.

2023-04-25 06:40 UTC, dg-concordium commented on source/mainnet/net/guides/run-node-ubuntu.rst
> +Since version 5.3.x of the node the collector uses the GRPC V2 interface. Therefore, in order to run the collector, it is required that the node which the collector connects to has the GRPC V2 interf
This x was what Ales requested in the PRs for Testnet release. So I did the same for mainnet Ubuntu for this release.

2023-04-25 06:41 UTC, dg-concordium commented on source/mainnet/net/guides/run-node-ubuntu.rst
> +Since version 5.3.x of the node the collector uses the GRPC V2 interface. Therefore, in order to run the collector, it is required that the node which the collector connects to has the GRPC V2 interf
https://github.com/Concordium/concordium.github.io/pull/783/files

2023-04-26 05:51 UTC, mh-concordium approved these changes
Looks good.

2023-04-27 05:43 UTC, merged