VSCode extension release
Concordium/concordium.github.io pull request #798
Opened 2023-04-19 11:28 UTC by dg-concordium

## Purpose

Inform users about the release of the VSCode extension

## Changes

Release notes, downloads, sc setup tools topic, developer resources topic.

## Checklist

- [X] My code follows the style of this project.
- [X] The code compiles without warnings.
- [X] I have performed a self-review of the changes.
- [ ] I have documented my code, in particular the intent of the
      hard-to-understand areas.
- [ ] (If necessary) I have updated the CHANGELOG.

## CLA acceptance

_Remove if not applicable.

By submitting the contribution I accept the terms and conditions of the
Contributor License Agreement v1.0
- link: https://developers.concordium.com/CLAs/Contributor-License-Agreement-v1.0.pdf

- [X] I accept the above linked CLA.

2023-04-23 20:06 UTC, abizjak approved these changes
Looks good, apart from the XX in the date of course.

2023-05-01 06:00 UTC, mh-concordium requested changes
Looks ok, I had a minor comment because I couldn't see weather checksum for cargo-concordium was changed.

2023-05-01 06:16 UTC, dg-concordium commented on source/mainnet/net/installation/downloads-testnet.rst
>        - SHA256 checksum of the download: :substitution-code:`|cargo-linux-checksum|`
It wasn't because the packages weren't built when I last touched this PR.

2023-05-01 06:29 UTC, abizjak approved these changes

2023-05-01 06:29 UTC, abizjak commented on source/mainnet/net/resources/release-notes-mainnet.rst
> +VSCode extension 1.0.0
This will be 1.0.1

2023-05-01 06:29 UTC, abizjak commented on source/mainnet/net/resources/release-notes.rst
> +VSCode extension 1.0.0
1.0.1

2023-05-01 07:23 UTC, concordium-cl approved these changes

2023-05-01 11:17 UTC, mh-concordium approved these changes
Looks good.

2023-05-01 12:44 UTC, merged