5.4.x testnet node release
Concordium/concordium.github.io pull request #820
Opened 2023-05-16 08:09 UTC by dg-concordium

## Purpose

Inform users about testnet node release.

## Changes

Release notes, testnet downloads, previous nodes

## Checklist

- [X] My code follows the style of this project.
- [X] The code compiles without warnings.
- [X] I have performed a self-review of the changes.
- [ ] I have documented my code, in particular the intent of the
      hard-to-understand areas.
- [ ] (If necessary) I have updated the CHANGELOG.

## CLA acceptance

_Remove if not applicable.

By submitting the contribution I accept the terms and conditions of the
Contributor License Agreement v1.0
- link: https://developers.concordium.com/CLAs/Contributor-License-Agreement-v1.0.pdf

- [X] I accept the above linked CLA.

2023-05-26 06:43 UTC, dg-concordium commented
This also contains the release for the client which will be for both testnet and mainnet, hence mainnet release notes.

2023-05-31 05:44 UTC, mh-concordium requested changes

2023-05-31 05:44 UTC, mh-concordium commented on source/mainnet/net/installation/downloads-testnet.rst
> +   - `Download the Testnet Windows Installer package <https://distribution.concordium.software/windows/Signed/Node-5.4.0-0.msi>`_
There is as new package for all the  distributions, we will release 5.4.1.

2023-05-31 05:44 UTC, mh-concordium commented on source/mainnet/net/installation/downloads-testnet.rst
> +      - SHA256 checksum of the download: ``62c24f7a2bc48ba31a7143f65d16f14b282b46940ebf093b1ffaaa258ba1a9da``
```suggestion
      - SHA256 checksum of the download: ``8c1f8df5c83999c10a4cda8f9d35f632f38c23aa797a50fcb4db3c591788b291``
```

2023-05-31 05:44 UTC, mh-concordium commented on source/mainnet/net/installation/downloads-testnet.rst
> +   - `Download the Testnet Debian package <https://distribution.testnet.concordium.com/deb/concordium-testnet-node_5.4.0-0_amd64.deb>`_
```suggestion
   - `Download the Testnet Debian package <https://distribution.testnet.concordium.com/deb/concordium-testnet-node_5.4.1-0_amd64.deb>`_
```

2023-05-31 05:44 UTC, mh-concordium commented on source/mainnet/net/installation/downloads-testnet.rst
> +   - `Download the Testnet Windows Installer package <https://distribution.concordium.software/windows/Signed/Node-5.4.0-0.msi>`_
```suggestion
   - `Download the Testnet Windows Installer package <https://distribution.concordium.software/windows/Signed/Node-5.4.1-0.msi>`_
```

2023-05-31 05:44 UTC, mh-concordium commented on source/mainnet/net/installation/downloads-testnet.rst
> +   - `Download the Testnet macOS installer package <https://distribution.concordium.software/macos/signed/concordium-node-5.4.0.pkg>`_
```suggestion
   - `Download the Testnet macOS installer package <https://distribution.concordium.software/macos/signed/concordium-node-5.4.1.pkg>`_
```

2023-05-31 10:59 UTC, abizjak approved these changes
I have some suggestions for making the changelogs a bit nicer.

Looks good otherwise.

2023-05-31 10:59 UTC, abizjak commented on source/mainnet/net/resources/release-notes-mainnet.rst
> +- Fixed a bug that caused another code-leftover to be displayed in the finalization proof line of the gas rewards section of the ``consensus show-chain-parameters`` output. This is only relevant when
```suggestion
- Fix a bug in display of ``consensus show-chain-parameters`` output for protocol version 6.
```

2023-05-31 10:59 UTC, abizjak commented on source/mainnet/net/resources/release-notes.rst
> +- Fixed a bug that caused another code-leftover to be displayed in the finalization proof line of the gas rewards section of the ``consensus show-chain-parameters`` output. This is only relevant when
```suggestion
- Fix a bug in display of ``consensus show-chain-parameters`` output for protocol version 6.
```

2023-05-31 10:59 UTC, abizjak commented on source/mainnet/net/resources/release-notes.rst
> +- Added ``raw GetBlockTransactionEvents`` that prints the list of transaction outcomes in a given block.
```suggestion
- Add ``raw GetBlockTransactionEvents`` that prints the list of transaction outcomes in a given block.
```

2023-05-31 10:59 UTC, abizjak commented on source/mainnet/net/resources/release-notes-mainnet.rst
> +- Added ``raw GetBlockTransactionEvents`` that prints the list of transaction outcomes in a given block.
```suggestion
- Add ``raw GetBlockTransactionEvents`` that prints the list of transaction outcomes in a given block.
```

2023-05-31 10:59 UTC, abizjak commented on source/mainnet/net/resources/release-notes.rst
> +- Do not use peer buckets when running as a normal node (not as a bootstrapper).
```suggestion
- Do not keep a historical list of peers when running as a normal node.
```

2023-06-01 09:45 UTC, merged