Mainnet node release 5.4.1
Concordium/concordium.github.io pull request #830
Opened 2023-06-02 08:04 UTC by dg-concordium

## Purpose

Inform users about the mainnet node release

## Changes

Release notes; update downloads, previous downloads, variables.

## Checklist

- [X] My code follows the style of this project.
- [X] The code compiles without warnings.
- [X] I have performed a self-review of the changes.
- [ ] I have documented my code, in particular the intent of the
      hard-to-understand areas.
- [ ] (If necessary) I have updated the CHANGELOG.

## CLA acceptance

_Remove if not applicable.

By submitting the contribution I accept the terms and conditions of the
Contributor License Agreement v1.0
- link: https://developers.concordium.com/CLAs/Contributor-License-Agreement-v1.0.pdf

- [X] I accept the above linked CLA.

2023-06-02 09:11 UTC, abizjak approved these changes
Looks good, but I'll defer to @mh-concordium to do a final check of links/hashes.

2023-06-13 06:11 UTC, concordium-cl approved these changes

2023-06-13 09:04 UTC, mh-concordium requested changes
Package version and checksum were changed.

2023-06-13 09:06 UTC, mh-concordium commented on source/mainnet/variables.rst
> +.. |mainnet-node-version| replace:: 5.4.1
```suggestion
.. |mainnet-node-version| replace:: 5.4.2
```

2023-06-14 08:46 UTC, merged