6.1.7 Testnet release
Concordium/concordium.github.io pull request #902
Opened 2023-10-13 09:08 UTC by dg-concordium

## Purpose

Inform users about 6.1.7 Testnet release

## Changes

Downloads
Variables
Release notes

## Checklist

- [X] My code follows the style of this project.
- [X] The code compiles without warnings.
- [X] I have performed a self-review of the changes.
- [ ] I have documented my code, in particular the intent of the
      hard-to-understand areas.
- [ ] (If necessary) I have updated the CHANGELOG.

## CLA acceptance

_Remove if not applicable.

By submitting the contribution I accept the terms and conditions of the
Contributor License Agreement v1.0
- link: https://developers.concordium.com/CLAs/Contributor-License-Agreement-v1.0.pdf

- [X] I accept the above-linked CLA.

2023-10-13 10:58 UTC, abizjak approved these changes

2023-10-16 11:35 UTC, mh-concordium requested changes
Please consider changes.

2023-10-16 11:35 UTC, mh-concordium commented on source/mainnet/net/installation/downloads.rst
> +      To run a node on macOS, `download a Testnet macOS installer package <https://distribution.concordium.software/macos/signed/concordium-node-6.1.7-0.pkg>`_.
```suggestion
      To run a node on macOS, `download a Testnet macOS installer package <https://distribution.concordium.software/macos/signed/concordium-node-6.1.7-1.pkg>`_.
```

2023-10-16 12:20 UTC, mh-concordium approved these changes
Looks good.

2023-10-16 13:39 UTC, merged