Company ID tool
Concordium/concordium.github.io pull request #934
Opened 2023-11-23 10:36 UTC by dg-concordium

## Purpose

Documentation for the company ID tool

## Changes

Change the company ID topic
Downloads

## Checklist

- [X] My code follows the style of this project.
- [X] The code compiles without warnings.
- [X] I have performed a self-review of the changes.
- [ ] I have documented my code, in particular the intent of the
      hard-to-understand areas.
- [ ] (If necessary) I have updated the CHANGELOG.

## CLA acceptance

_Remove if not applicable.

By submitting the contribution I accept the terms and conditions of the
Contributor License Agreement v1.0
- link: https://developers.concordium.com/CLAs/Contributor-License-Agreement-v1.0.pdf

- [X] I accept the above linked CLA.

2023-11-23 14:01 UTC, mh-concordium requested changes

2023-11-24 05:45 UTC, dg-concordium commented on source/mainnet/net/guides/company-identities.rst
> +         }
This is an old code example. We should probably have a new one. I will replace it with mine.

2023-11-24 05:55 UTC, dg-concordium commented on source/mainnet/net/guides/company-identities.rst
> +         }
I have changed it. Please review. I also removed the part about encrypted transfers.

2023-11-24 08:04 UTC, abizjak approved these changes
Looks good. Just a few leftovers from the old flow that need to be cleaned up.

2023-11-24 08:04 UTC, abizjak commented on source/mainnet/net/guides/company-identities.rst
> +However, if the ``account-keys.json`` file is not encrypted it can be imported into ``concordium-client`` with the command:
In the command-line below, you should remove the `--format=genesis`. It is not longer needed (and also cannot be there).

2023-11-24 08:04 UTC, abizjak commented on source/mainnet/net/guides/company-identities.rst
> +However, if the ``account-keys.json`` file is not encrypted it can be imported into ``concordium-client`` with the command:
And in the line below that one remove the fact that `--name` is optional. It is mandatory now.

2023-11-24 08:04 UTC, abizjak commented on source/mainnet/net/guides/company-identities.rst
The account-keys file can no longer be encrypted either.

2023-11-24 11:04 UTC, merged

2023-11-24 11:08 UTC, mh-concordium approved these changes
Looks good.