SubQuery Featured
Concordium/concordium.github.io pull request #936
Opened 2023-11-23 16:08 UTC by bgodlin

## Purpose

Hello Concordium team,

We are submitting this contribution with the intention of incorporating SubQuery into your project documentation. As you can observe, we have already prepared the initial project. Kindly inform us if any adjustments are necessary on our part.

## Changes

We established a distinct category `Indexers` because of their crucial role in querying historical data. We incorporated our indexer by referring to pre-existing quickstart guides and starter projects.

## Checklist

- [x] My code follows the style of this project.
- [x] The code compiles without warnings.
- [x] I have performed a self-review of the changes.
- [x] I have documented my code, in particular the intent of the
      hard-to-understand areas.
- [ ] (If necessary) I have updated the CHANGELOG.

2023-11-24 12:21 UTC, dg-concordium requested changes
I think I forgot to mention that we use US English. Sorry about that.

2023-11-24 12:21 UTC, dg-concordium commented on source/mainnet/net/indexers/intro.rst
> +Indexers, in a broad context, play a fundamental role in organising and optimising data retrieval within various systems. These tools act as navigational aids, allowing efficient access to specific i
```suggestion
Indexers, in a broad context, play a fundamental role in organizing and optimizing data retrieval within various systems. These tools act as navigational aids, allowing efficient access to specific information by creating structured indexes. In the realm of databases and information management, indexers enhance query performance by creating a roadmap to swiftly locate data entries. 
```

2023-11-24 12:21 UTC, dg-concordium commented on source/mainnet/net/indexers/intro.rst
> +In the context of blockchain and dApps, indexers go beyond traditional databases, facilitating streamlined access to on-chain data. This includes transaction histories, smart contract states, and eve
```suggestion
In the context of blockchain and dApps, indexers go beyond traditional databases, facilitating streamlined access to on-chain data. This includes transaction histories, smart contract states, and event logs. In the dynamic and decentralized world of blockchain, indexers contribute to the efficiency of data queries, supporting real-time updates and ensuring the seamless functionality of diverse applications and platforms.
```

2023-11-24 12:21 UTC, dg-concordium commented on source/mainnet/net/indexers/intro.rst
> +There are several indexer solutions available, each offering different levels of decentralisation, ease of development, and performance for you to consider. These solutions serve as intermediaries to
```suggestion
There are several indexer solutions available, each offering different levels of decentralization, ease of development, and performance for you to consider. These solutions serve as intermediaries to assist in indexing the Concordium network.
```

2023-11-24 12:21 UTC, dg-concordium commented on source/mainnet/net/indexers/subquery.rst
> +SubQuery is a leading blockchain data indexer that provides developers with fast, flexible, universal, open source and decentralised APIs for web3 projects. SubQuery SDK allows developers to get rich
```suggestion
SubQuery is a leading blockchain data indexer that provides developers with fast, flexible, universal, open-source, and decentralized APIs for web3 projects. SubQuery SDK allows developers to get rich indexed data and build intuitive and immersive decentralized applications in a faster and more efficient way. SubQuery supports 100+ ecosystems including Concordium, Ethereum, Polygon, Polkadot, Algorand, NEAR, and Avalanche.
```

2023-11-24 12:21 UTC, dg-concordium commented on source/mainnet/net/indexers/subquery.rst
> +Another one of SubQuery's competitive advantages is the ability to aggregate data not only within a chain but across multiple blockchains all within a single project. This allows the creation of feat
```suggestion
Another of SubQuery's competitive advantages is the ability to aggregate data not only within a chain but across multiple blockchains all within a single project. This allows the creation of feature-rich dashboard analytics and multi-chain block scanners.
```

2023-11-24 12:21 UTC, dg-concordium commented on source/mainnet/net/indexers/subquery.rst
> +Other advantages include superior performance with multiple RPC endpoint configurations, multi-worker capabilities and a configurable caching architecture. To find out more, visit our [documentation]
```suggestion
Other advantages include superior performance with multiple RPC endpoint configurations, multi-worker capabilities, and a configurable caching architecture. To find out more, visit SubQuery's `documentation <https://academy.subquery/>`_.
```

2023-11-24 12:21 UTC, dg-concordium commented on source/mainnet/net/indexers/subquery.rst
> +You can also follow along this [step by step guide](https://academy.subquery.network/quickstart/quickstart.html) to get familiar with SubQuery.
```suggestion
You can also follow this [step-by-step guide](https://academy.subquery.network/quickstart/quickstart.html) to get familiar with SubQuery.
```

2023-11-24 12:21 UTC, dg-concordium commented on source/mainnet/net/indexers/subquery.rst
> +---------------------
```suggestion
-----------------------------------------------------------------------
```

2023-11-24 12:21 UTC, dg-concordium commented on source/mainnet/net/indexers/subquery.rst
> +- You can publish it to SubQuery's enterprise-level [Managed Service](https://managedservice.subquery.network/), where we'll host your SubQuery project in production ready services for mission critic
```suggestion
- You can publish it to SubQuery's enterprise-level [Managed Service](https://managedservice.subquery.network/), where we'll host your SubQuery project in production ready services for mission critical data with zero-downtime blue/green deployments. There is even a generous free tier. [Find out how](https://academy.subquery.network/run_publish/publish.html).
```

2023-11-24 12:21 UTC, dg-concordium commented on source/mainnet/net/indexers/subquery.rst
> +- You can publish it to the decentralised [SubQuery Network](https://subquery.network/network), the most open, performant, reliable, and scalable data service for dApp developers. The SubQuery Networ
```suggestion
- You can publish it to the decentralized [SubQuery Network](https://subquery.network/network), the most open, performant, reliable, and scalable data service for dApp developers. The SubQuery Network indexes and services data to the global community in an incentivized and verifiable way and supports Concordium from launch.
```

2023-11-26 14:42 UTC, abizjak commented on source/mainnet/net/indexers/subquery.rst
> +- Locally on your own computer (or a cloud provider of your choosing), [view the instructions on how to run SubQuery Locally](https://academy.subquery.network/run_publish/run.html).
Please use RST link syntax.
```suggestion
- Locally on your own computer (or a cloud provider of your choosing), `view the instructions on how to run SubQuery Locally <https://academy.subquery.network/run_publish/run.html>`_.
```

2023-11-27 07:28 UTC, dg-concordium approved these changes

2023-11-27 11:32 UTC, abizjak approved these changes

2023-12-01 07:43 UTC, merged