Add links to SC videos
Concordium/concordium.github.io pull request #956
Opened 2024-01-03 11:42 UTC by dg-concordium

## Purpose

Add the recently published smart contract tutorial videos to the documentation.

## Changes

Added links to videos where needed in documentation.

## Checklist

- [X] My code follows the style of this project.
- [X] The code compiles without warnings.
- [X] I have performed a self-review of the changes.
- [ ] I have documented my code, in particular the intent of the
      hard-to-understand areas.
- [ ] (If necessary) I have updated the CHANGELOG.

## CLA acceptance

_Remove if not applicable.

By submitting the contribution I accept the terms and conditions of the
Contributor License Agreement v1.0
- link: https://developers.concordium.com/CLAs/Contributor-License-Agreement-v1.0.pdf

- [X] I accept the above linked CLA.

Closes #945

2024-01-03 14:46 UTC, Bargsteen requested changes
Looks good apart from the upgradable section 😊

2024-01-03 14:46 UTC, Bargsteen commented on source/mainnet/smart-contracts/guides/upgradeable-contract.rst
> +
We currently don't have a video about making smart contracts upgradable. 
```suggestion
```

2024-01-08 08:52 UTC, dg-concordium commented
> Looks good apart from the upgradable section 😊

I think that I forgot to remove it when I had originally asked you if that's what the video was before I watched it. Glad you caught it.

2024-01-08 10:38 UTC, Bargsteen approved these changes

2024-01-08 10:47 UTC, merged