Documentation of things that are not up to date.
Concordium/concordium.github.io pull request #99
Opened 2021-04-29 13:59 UTC by eb-concordium

## Purpose

To update documentation of things that are not up to date.

## Changes

So far a bit of documentation has been added regarding the `--signers` option for transaction and that accounts are owned by credential holders. Credential holders are added to the glossary.

2021-05-03 07:18 UTC, abizjak commented on source/testnet/references/transactions.rst
> +   it will sign with all keys in the local config.
```suggestion
   ``concordium-client`` will sign with all keys in the local configuration.
```

2021-05-20 09:33 UTC, LotteKh approved these changes

2021-05-20 19:30 UTC, LotteKh requested changes
I added one suggestion to manage accounts.

2021-05-21 06:17 UTC, LotteKh commented on source/testnet/references/manage-accounts.rst
>  :ref:`off-chain<glossary-off-chain>` part.
I think the old and the new sentence were mixed up. Here's what it should look like:

An account on the Concordium blockchain is owned by one or more :ref:`credential holders<glossary-credential-holder>` and consists of two parts: The :ref:`on-chain<glossary-on-chain>` part, which is publicly visible and maintained by the bakers, and the :ref:`off-chain<glossary-off-chain>` part.

2021-05-21 08:28 UTC, LotteKh approved these changes

2021-05-21 08:55 UTC, abizjak approved these changes

2021-05-21 09:16 UTC, merged